### ISSUE TITLE
add "patch" as fix type

### ISSUE THREAD

**Issue by NikOverflow** [thenativeweb/get-next-version#120]
It would be great if you add "patch" as a fix type.
In my opinion, patch sounds better than fix and should perhaps also be added.

**Comment by goloroden** [comment]
AFAICS patch is not part of the official spec, is it?

**Comment by NikOverflow** [comment]
> AFAICS patch is not part of the official conventional commit spec, is it?

Not really but it would be cool if you add it or add an option to change the types for actions.

**Comment by goloroden** [comment]
I think that we are going to stick with the standard here (especially since it's much easier to change the prefix of the commit message to `fix`, instead of introducing, testing, documenting and maintaining a new option).

Anyway, thanks for the suggestion and sharing your idea 😊
