### ISSUE TITLE
ignores latest major version

### ISSUE THREAD

**Issue by ReLehmann** [thenativeweb/get-next-version#126]
### What happened incorrectly?

The repository has the following tags, but the next version is 0.16.0 and not 1.x.0. Comprehension problem on my part?

0.0.1
0.1.0
0.10.0
0.11.0
0.12.0
0.13.0
0.14.0
0.15.0
0.2.0
0.3.0
0.4.0
0.5.0
0.6.0
0.7.0
0.8.0
0.9.0
1.0.0

**Comment by goloroden** [comment]
Can you please provide a repository where we can reproduce this?

**Comment by ReLehmann** [comment]
Unfortunately not, as it is a private repository. But we can have a look together if it helps.

**Comment by goloroden** [comment]
Can you please setup a publicly accessible sample repository (or invite me to a private one)?

**Comment by ReLehmann** [comment]
I'll try to recreate this in a separate repository that I can give you rights to.

**Comment by ReLehmann** [comment]
Unfortunately, we can't get it cleaned up enough to share the repository. We'll have to look around for an alternative first. Thanks for the feedback.
