### ISSUE TITLE
commit was tagged with multiple semver versions

### ISSUE THREAD

**Issue by mrkskwsnck** [thenativeweb/get-next-version#34]
Version: 2.0.0
System: linux-amd64

I ran this nice command for a [20 year old repo](https://github.com/ILIAS-eLearning/ILIAS) to see what happens and it gave me this:

```
user@host:~$ get-next-version 
12:59PM FTL commit was tagged with multiple semver versions
```

Any chance to find out the offending commit?

**Comment by goloroden** [comment]
Hey @mrkskwsnck 👋 

Thanks for bringing up this issue – and I'm pretty impressed that you use our tool on such a large and old repository, thanks 😊

Regarding your problem – I've already created a fix, so that the commit ID will be shown. As soon as it has been reviewed, we'll release a new version.

**Comment by goloroden** [comment]
@mrkskwsnck This is fixed now and part of the `2.1.0` release.

**Comment by mrkskwsnck** [comment]
@goloroden I confirm, now the commit ID comes with the message.

```
user@host:~$ get-next-version
11:02AM FTL commit 521d3528feee0e1003cf47903847bd8089f307e0 was tagged with multiple semver versions
```

**Comment by mrkskwsnck** [comment]
There's one more thing 😅

Inspecting [that particular commit](https://github.com/ILIAS-eLearning/ILIAS/commit/521d3528feee0e1003cf47903847bd8089f307e0) (that led to this issue) reveals the following commit message:

```
Adding come comments (github test)
```

As I understand, `test`might be one of valid tags. But what tag is the further one? Unfortunately, I don't understand the Go code of the commit message tag parser 😓

**Comment by dotKuro** [comment]
Hey @mrkskwsnck,
I had a look at the repository and the commit. Neither `github` nor `test` are tags for the commit. The parentheses are simply part of the commit message. The best way to find all the tags for the commit is to clone the repository and run `git tag --points-at <COMMIT-HASH>` locally. I did this:

```sh
kuro@cyriaxo ~/Projects/ILIAS (git)-[release_7] % git tag
 --points-at 521d3528feee0e1003cf47903847bd8089f307e0
4.3.5
4.3.8
4.4.3
```

It seems like for what ever reason the same commit was tagged with multiple versions (even as far as a feature version apart). I don't really know why it was done this way, but the behavior of `get-next-version` is as intended. 

I agree though, that is unfortunate that  `get-next-version` is incompatible with repositories that have these errors so far in the past. Maybe there is a way for us, to refactor the tool, to only include the relevant history for this specific check, but I am not making any promises for it to be implemented soon.

**Comment by mrkskwsnck** [comment]
Ah, that makes sense. Obviously, I misunderstood the message. Because I was thinking of _conventional commit **tags**_ instead of _git **tags**_ 🙄 Sorry for that and thank you for clarifying that for me.

In fact, I just was curious what version this tool might generate. The repo has quite a history, indeed. Who knows, what led to that particular commit getting tagged by multiple versions 🤷🏼
