### ISSUE TITLE
How to deal with merge commits?

### ISSUE THREAD

**Issue by coco1979ka** [thenativeweb/get-next-version#42]
Hi,

after watching your video, I was trying to implement semantic versioning with a Bitbucket pipeline. As we're also working with feature branches and pull requests, I found an issue when merging back to master. In the master build pipeline I try to get the next version but unfortunately - by default - the merge commit itself is not semantic version friendly. In theory all information is present up to the merge commit and the merge commit itself just needs the tag for the next version.

![image](https://user-images.githubusercontent.com/5807679/184608383-66b50c7f-4726-44b8-880d-44eea3bf2dc9.png)

So what would be the best strategy to make it work smoothly?

My thoughts:

1. Use fast forward merges: Would work, but usually we prefer merge commits instead of fast forward merges
2. Modify the commit message for the merge to something which does not modify the version (like chore). As there is no way to force this, each developer must be double careful with merging
3. Allow to ignore messages with a certain pattern and just use the commit messages before the latest commit, calculate the version, tag it in the repository and then version calculation would work again.

Happy to hear your thoughts.

**Comment by goloroden** [comment]
Hi @coco1979ka 👋 

Sorry for the late answer.

It's true that the default merge commit message doesn't follow conventional commit format. However, this isn't a problem, since by default commits that do not match the expected format are ignored anyway. So as long as you get all the other commits over it should work as expected.

What we at *the native web* are doing is that we are using squash+merge, and we actually edit the message to match the expected format.

Hops this helps 😊

**Comment by coco1979ka** [comment]
Hi @goloroden,

thanks for your reply - if I understand correctly you only use conventional commits for the merges then, correct? I mean it makes sense, as you're usually only develop one feature/bugfix in a particular branch. 

One way for option 3 would be to calculate the version in the pull request pipeline (assuming all commit messages in a branch follow conventional commits, which could be forced by hooks), write it into a file and then use it in the merge commit to tag the version. The only problem I can see with this approach is, that it could lead to conflicts, when to PRs are open at the same time - both pointing to a different version.  

So it would be nice if the get-next-version could at least ignore non conventional commit messages (optionally). Maybe this could be a feature request 🙂

**Comment by goloroden** [comment]
> if I understand correctly you only use conventional commits for the merges then, correct?

Correct.

> So it would be nice if the get-next-version could at least ignore non conventional commit messages

It already does 😊

It simply considers everything that does not match a conventional commit style message to be a `chore` (which in turn does not lead to a new version).
