### ISSUE TITLE
Version is stuck

### ISSUE THREAD

**Issue by mrkskwsnck** [thenativeweb/get-next-version#44]
The version of my repo won't increment. Or do I miss something?

**Problem**

```bash
mkdir foo
cd foo
git init
# Initialized empty Git repository in ~/foo/.git/
touch bar
git add .
git commit -m 'fix: bar'
# [master (root-commit) 0afb43a] fix: bar
#  1 file changed, 0 insertions(+), 0 deletions(-)
#  create mode 100644 bar
get-next-version 
# 0.0.1
touch baz
git add .
git commit -m 'fix: baz'
# [master 9415c01] fix: baz
#  1 file changed, 0 insertions(+), 0 deletions(-)
#  create mode 100644 baz
get-next-version 
# 0.0.1
```

As you can see above, I made two fix commits, but the version is stuck with 0.0.1. I was expecting an version increment to 0.0.2.

**Environment**

```bash
lsb_release -a
# No LSB modules are available.
# Distributor ID:	Debian
# Description:	Debian GNU/Linux 11 (bullseye)
# Release:	11
# Codename:	bullseye
git version
# git version 2.30.2
get-next-version version
# get-next-version 2.1.1
# Revision 84f8bbc1964f4aa81eb09f4c94958340c5c58df5
```

**Comment by goloroden** [comment]
The behavior you observed is correct: Two fixes do not lead to two versions, unless you release a version after the first fix.

**Comment by mrkskwsnck** [comment]
Oh… kay, so indeed I did miss something 😓  Namely to release a version by tagging a commit. Thank you for clarifying that detail for me. Sorry for bothering you.

**Comment by goloroden** [comment]
Don’t worry 😉
