### ISSUE TITLE
Verify that the prefix does not contain invalid characters

### ISSUE THREAD

**Issue by goloroden** [thenativeweb/get-next-version#70]
### What is this feature about?

Since #68 we can use prefixes for version numbers, but right now it is possible to use values that e.g. only consist of whitespace. We should think about what characters are valid, and only allow those.

### What needs to be done to implement this feature?

- [ ] Decide which characters to allow
- [ ] Add a check to the flag
- [ ] Add / adjust tests
- [ ] Update documentation

**Comment by fsrv-xyz** [comment]
Hi @goloroden 👋 

I have made some thoughts about this topic.
One option would be to allow any valid tag characters (http://practicalseries.com/1002-vcs/02-06-concept.html#2.6.4) and give the user the control to specify there own rules.

The second option would be to only allow the `v` prefix due to other options are not not widely used (in my corner of the programming world).

However, prefixed versions are not in semantic versioning schema anyway. (https://semver.org/#is-v123-a-semantic-version)

**Comment by goloroden** [comment]
Hey @fsrv-xyz 👋 

Thanks for thinking about this one.

Since a `v` as prefix is not valid according to semantic versioning anyway, I don't see a good reason why we should add support especially for this case, and not for all other (invalid, but maybe for whatever reasons required) cases as well.

So I basically like the idea you brought up with allowing everything that is valid within a Git tag. TBH I don't have in mind what the allowed characters are, but I'd assume it covers:

- uppercase characters
- lowercase characters
- underscore and dash characters
- maybe numbers (although this, TBH, doesn't make too much sense in front of a version number)

Would you be interested in adding an allow list of characters and adding a validity check?

**Comment by fsrv-xyz** [comment]
I agreeing with your point of view. Checking for the prefix as independent git tag (with a few exceptions) would do the job best.
I like to take care of the implementation of the functionality / tests / documentation. 😃

**Comment by goloroden** [comment]
Wow, that's great 🎉

Thanks for your help, and I'm looking forward to the next PR 😊

(Oh, and btw: Since the build is currently broken (see #71): I think we'll fix this tomorrow)

**Comment by fsrv-xyz** [comment]
@goloroden Thank you for merging the feature. Unfortunately, [the build process](https://github.com/thenativeweb/get-next-version/actions/runs/3623368606/jobs/6109152500) seems to be broken. 
On my machine, the build works with environment variable `CGO_ENABLED` set to `1`.

**Comment by goloroden** [comment]
TBH I'm wondering why it failed, since the QA workflow passed (and `main` worked as well).

Theoretically, the environment variable should not be needed – neither by your changes nor by the previously existing code. We'll have to find out what causes problems here.

Anyway, I'm going to close this issue as its implementation has been done. Thanks again for your help and support 😊

**Comment by goloroden** [comment]
PS: I already found the problem – it's a dependency that we updated, which now causes this issue. I'm going to fix it soon.
